M48
; DRILL file {KiCad (6.0.2)} date Sat Mar 12 22:50:11 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-12T22:50:11+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X167.64Y-66.04
X218.44Y-20.32
X228.6Y-20.32
X228.6Y-66.04
T2
X221.69Y-54.015
X221.69Y-65.445
T0
M30
